name: Build COSMOS hooks

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: d3fau4/nx-dev:latest
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: true

    - name: Build app
      run: |
        ./exlaunch.sh build
        
    - uses: actions/upload-artifact@v3.1.1
      with:
        name: Aiba-nx
        path: deploy/
